### ISSUE TITLE
authenticate using session

### ISSUE THREAD

**Issue by tmanolat** [ApostolisHD/GrailsEmployee2#1]
https://github.com/ApostolisHD/GrailsEmployee2/blob/ac9aa8c422697311f59de9417c86279668937736/grails-app/controllers/grailsemployee/SecurityInterceptor.groovy#L12

το authentication γίνεται μέσω sessions - οχι απο την βάση

επισης το session είναι θεμα controller μόνο

**Comment by ApostolisHD** [comment]
https://github.com/ApostolisHD/GrailsEmployee2/blob/bacd4ac64b57b4c4f38d09c3a6c7bb1753001306/grails-app/controllers/grailsemployee/SecurityInterceptor.groovy#L12

Ετοιμο
