### ISSUE TITLE
Multiline sql παντου

### ISSUE THREAD

**Issue by tmanolat** [ApostolisHD/GrailsEmployee2#2]
https://github.com/ApostolisHD/GrailsEmployee2/blob/ac9aa8c422697311f59de9417c86279668937736/grails-app/services/grailsemployee/UserService.groovy#L29

τα sql πρέπει να είναι σε multiline GStrings ώστε να είναι readable - όχι μια πλατιά γραμμή

```
select *
from mytable
where id = ${id}
```

**Comment by ApostolisHD** [comment]
https://github.com/ApostolisHD/GrailsEmployee2/blob/ce82d9b4a47423c137d6c44dcaf444f44f623734/grails-app/services/grailsemployee/UserService.groovy#L34

ok ετοιμο
