### ISSUE TITLE
user proper HTTP result Codes

### ISSUE THREAD

**Issue by tmanolat** [ApostolisHD/GrailsEmployee2#21]
https://github.com/ApostolisHD/GrailsEmployee2/blob/6b8720b7d11777b585c86422537afe6af1115507/grails-app/controllers/grailsemployee/AuthenticationApiController.groovy#L24

πρέπει να είναι στην οικογένεια των 40Χ αν θυμάμαι...

δείτε https://restfulapi.net/http-status-codes/
μαλλον 401 επρεπε επομένως...

**Comment by ApostolisHD** [comment]
ETA 1/4/2021 14:00
