### ISSUE TITLE
what if invalid id?

### ISSUE THREAD

**Issue by tmanolat** [ApostolisHD/GrailsEmployee2#23]
https://github.com/ApostolisHD/GrailsEmployee2/blob/6b8720b7d11777b585c86422537afe6af1115507/grails-app/controllers/grailsemployee/DepartmentApiController.groovy#L21

should return 404 on not found and 500 on error (try -catch?)

**Comment by ApostolisHD** [comment]
ETA 1/4/2021 15:00
