### ISSUE TITLE
forms must be POST

### ISSUE THREAD

**Issue by tmanolat** [ApostolisHD/GrailsEmployee2#3]
https://github.com/ApostolisHD/GrailsEmployee2/blob/ac9aa8c422697311f59de9417c86279668937736/grails-app/views/user/edit.gsp#L14

παντού - πρέπει να είναι post οι φόρμες

**Comment by ApostolisHD** [comment]
https://github.com/ApostolisHD/GrailsEmployee2/blob/f6a8266b77151562065f422ff7a7f92c50813d0f/grails-app/views/user/edit.gsp#L14

εκανε ποστ η φορμα αλλα για το clarification
