### ISSUE TITLE
να αλλαξει σε ένα user object 

### ISSUE THREAD

**Issue by tmanolat** [ApostolisHD/GrailsEmployee2#4]
https://github.com/ApostolisHD/GrailsEmployee2/blob/bacd4ac64b57b4c4f38d09c3a6c7bb1753001306/grails-app/controllers/grailsemployee/SecurityInterceptor.groovy#L12

και δεν χρεάζεται getAttribute - δες τα docs
`req.session`

**Comment by ApostolisHD** [comment]
22a3d7b7ac680bf42ecd23738811ab23af14c401

Ετοιμο!
